### ISSUE TITLE
api count issues

### ISSUE THREAD

**Issue by rylxes** [InfyOmLabs/laravel-routes-explorer#2]
the api count doesn't work out of the box until i add : `\InfyOm\RoutesExplorer\Middleware\RoutesExplorerMiddleware::class,`  in my middleware, ....

i think documentation should be updated to show that

**Comment by Defrothew** [comment]
Yes, I can confirm that this step is missing in the documentation. For those who are having the same issues. You can add the following code in your app/RouteServiceProvider.php file.

Inside the RouteServiceProvider's boot method:
> 
        $router = $this->app['router'];
        $router->pushMiddlewareToGroup('api', RoutesExplorerMiddleware::class);

Adding this namespace as well:
> 
        use InfyOm\RoutesExplorer\Middleware\RoutesExplorerMiddleware;

That should be able to help you start tracking API calls.
