### ISSUE TITLE
this package will not install on generator-builder

### ISSUE THREAD

**Issue by leerlemoniii** [InfyOmLabs/laravel-routes-explorer#4]
Your requirements could not be resolved to an installable set of packages.
Conclusion: remove laravel/framework v6.2.0

**Comment by erdincgc** [comment]
same here

**Comment by mitulgolakiya** [comment]
We will add support for Laravel 6 soon.

**Comment by ajayinfyom** [comment]
Added Support of Laravel Version 6+
